variables:

- group: Appdome




trigger:

- main

steps:

- task: DownloadSecureFile@1

  name: App

  displayName: 'Download App'

  inputs:

    secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1

  name: keystore

  displayName: 'Download Keystore'

  inputs:

    secureFile: 'appdome.keystore'

# - task: DownloadSecureFile@1

#   name: keystore

#   displayName: 'Download Keystore'

#   inputs:

#     secureFile: 'AppdomeLabs-Android-Signing.jks'

- task: Build-2Secure@0
  inputs:
    Platform: 'android'
    Sign: 'signOnAppdome'
    App: 'https://appdome-automation-vanilla-apps.s3.eu-central-1.amazonaws.com/Thomas/app-uat-release.aab?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEOz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGV1LWNlbnRyYWwtMSJHMEUCIHde25nvAwsbQZ8LSM1Vm1aGdZC2IYZqvoB7mlHxjZ%2BdAiEA52aVE0OPbbJTw8jP2TSXvvD7i2BkzjAnQDmyrEpEJoEqgQMIdRAAGgwzMDIyNjc2NTQzOTQiDG5euZw0XFYWefNLWSreAgUHDb4Dh%2FWYwkULa1e5dgx8TU%2FtGkqnq%2F9PJfRqmXMrHQBqeUGdmh%2FFVckbdjCDZzZ5YJHOv8QJ6rTa%2BiG%2FRA6rflEWv5Cebdi2AQvCLgW40Xd%2B%2FZ%2FnG%2FCmViXRQ1SKYY2eIK5VqQITB9qOfI5WmyTT4KpBnWU4wAddEf54QbZd%2FYlZLLwNtH0r7V6ixqxs4hoRbRiptwDb13lPMHwWrVEq%2F2aLROlcMFXZ7feAksY4IC%2F6RItO811gEBuBrD%2BAh24d9ZSOI5i1PvJ%2BLS%2BLd5eghqxzOO6KBZmbqURZyiHgMmYqv2Gx%2BMvou4l3XfrH9Nu6lcNHDLcdvK4whMvLgCorEDYBYl4eTxKgLeyH2IJE%2BYBJ9Ym%2Baxu7Bgq0t5%2BgKpPbTJhZC9VfC2aT3wcCDd8xzh3S3q4j86cUOHiGwFRN4K3G2U5ytIXRAAkAKckxMEWNh3KChxhRZvqIQcJ1MNf62aUGOrMCYsFC0J2GCB7id8eiGjECMul76YkmGwj3aZvzId6JMQuZ03cUXvf17BNLG%2B3DT1di%2B7g8TiawvEgHl%2BWbE2tdOBQM5K9%2BQIuQFoJ5SFYThZOEPvqhSIZ6WZPwenBli6RYuWsYKR4oB9G733FkHQgu1nhC83LOsXPxI%2BVhnBZ2JjRDDKomDoRnA1Gnu1F6NzQNYxXerwGBv1XvA%2Fa4qwetM0Ek496dtjPovw7I67Ky0aluD96yC7rruFE3M0U8jSiCHF%2BJtovrxdifVFBRe3o2gNuOWjxw8YOamPqKubLAnBsJknmhrJ5TGIISy2GP9ZmjtO5SZkprRVJjLveankzKZD2WMHKjA25w54vF%2FxI%2BacffNB2qN%2FGpdNwoXVve2pveLITPBI8Rsqa5g3ZHPOH6AfYweA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230718T115412Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAUMYEOMD5CRU3HHKU%2F20230718%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Signature=cd74a79585988985ecaaeb5378388df97266c6d92f4fc29c03a350024bc36102'
    Token: '$(Token)'
    FusionSetId: '$(Android_fusion_set)'
    TeamId: '82ad8de0-23bc-11ee-a89e-93318e80f6c9'
    KeystoreFile: '$(keystore.secureFilePath)'
    KeystorePass: 'appdome'
    KeystoreAlias: 'appdome'
    KeyPass: 'appdome'
    SecondOutput: true
  name: buildTask
- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'Appdome Output'




- script: |

   echo "Built APK file: $(buildTask.AppdomeSecuredApp)"
   echo "Built APK file: $(buildTask.AppdomeSecondOutput)"