variables:

- group: Appdome




trigger:

- main

steps:

- task: DownloadSecureFile@1

  name: App

  displayName: 'Download App'

  inputs:

    secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1

  name: keystore

  displayName: 'Download Keystore'

  inputs:

    secureFile: 'appdome.keystore'

# - task: DownloadSecureFile@1

#   name: keystore

#   displayName: 'Download Keystore'

#   inputs:

#     secureFile: 'AppdomeLabs-Android-Signing.jks'

- task: Build-2Secure@0
  inputs:
    Platform: 'android'
    Sign: 'signOnAppdome'
    App: '$(App.secureFilePath)'
    Token: '$(Token)'
    FusionSetId: '$(Android_fusion_set)'
    TeamId: '82ad8de0-23bc-11ee-a89e-93318e80f6c9'
    KeystoreFile: '$(keystore.secureFilePath)'
    KeystorePass: 'appdome'
    KeystoreAlias: 'appdome'
    KeyPass: 'appdome'
    SecondOutput: true
    OutputFileName: "My_App_for_testing"
  name: buildTask


- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'Appdome Output'




- script: |

   echo "Built APK file: $(buildTask.AppdomeSecuredApp)"
   echo "Built APK file: $(buildTask.AppdomeSecondOutput)"