variables:

- group: Appdome




trigger:

- main




steps:

- task: DownloadSecureFile@1

  name: App

  displayName: 'Download App'

  inputs:

    secureFile: 'TimeCard.apk'

- task: DownloadSecureFile@1

  name: keystore

  displayName: 'Download Keystore'

  inputs:

    secureFile: 'appdom e.keystore'




- task: Build-2Secure@0

  inputs:

    Platform: 'android'

    Sign: 'signOnAppdome'

    App: 'TimeCard.apk'

    Token: '$(Token)'

    FusionSetId: '$(Android_fusion_set)'
    # FusionSetId: '777'

    KeystoreFile: '$(keystoreFile.secureFilePath)'

    KeystorePass: 'appdome'

    KeystoreAlias: 'appdome'

    KeyPass: 'appdome'

    BuildWithLogs: true

  name: buildTask




- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'Appdome Output'




- script: |

   echo "Built APK file: $(buildTask.AppdomeSecuredApp)"